### ISSUE TITLE
swapOwner can fail in CPKFactory

### ISSUE THREAD

**Issue by hexyls** [gnosis/contract-proxy-kit#132] opened 2020-11-09 04:38 UTC
If the estimated gas for `createProxyAndExecTransaction` is too low [`swapOwner`](https://github.com/gnosis/contract-proxy-kit/blob/master/contracts/CPKFactory.sol#L46) can fail silently during `execTransaction` to Gnosis Safe v1.2.0 while not rolling back the whole transaction.

Users can potentially lose funds if they transfer assets to the proxy and ownership of the proxy is not successfully assigned to the user.

Transfer of ownership is not verified after the `swapOwner` call. We should probably check the return value of `execTransaction` to check if the transaction was successful.

[example transaction](https://dashboard.tenderly.co/tx/rinkeby/0x7649b7575bec5dcd305da32f323aaa888dc02f3a00c4bffeda892df021bf5994)

Should be considered for https://github.com/gnosis/contract-proxy-kit/pull/126

**Comment by cag** [comment] 2020-11-10 21:54
Closing this as this is a duplicate of #90

**Closed by cag** 2020-11-10 21:54 UTC

**Comment by hexyls** [comment] 2020-11-10 22:36
Ahh cool didn't see that thanks @cag
